esphome:
  name: wfd4001-682a
  friendly_name: WFD4001-682a

packages:
  wfd4001: !include
    file: common/wfd4001.yaml
    vars:
      component: fan
      component_friendly_name: Fan
  wifi: !include
    file: common/wifi.yaml
    vars:
      static_ip: 192.168.2.15
